import Foundation

enum puzzle: String {
    case rubiks = "3x3x3"
    case twoByTwo = "2x2x2"
    case fourByFour = "4x4x4"
    case fiveByFive = "5x5x5"
    case sixBySix = "6x6x6"
    case sevenBySeve = "7x7x7"
    case eightByEight = "8x8x8"
    case nineByNine = "9x9x9"
    case tenByTen = "10x10x10"
    case elevenByEleven = "11x11x11"
    case rubiksBlindfolded = "3x3x3 Blindfolded"
    case rubiksOneHanded = "3x3x3 One-Handed"
    case rubiksWithFeet = "3x3x3 With Feet"
    case megaminx = "Megaminx"
    case pyraminx = "Pyraminx"
    case squareOne = "Square-1"
    case skewb = "Skewb"
    case gearCube = "Gear Cube"
    case rubiksClock = "Rubik's Clock"
    case twoByTwoBlindfolded = "2x2x2 Blindfolded"
    case fourByFourBlindfolded = "4x4x4 Blindfolded"
    case fiveByFiveBlindfolded = "5x5x5 Blindfolded"
    case siameseCube = "Siamese Cube"
    case speedStacker = "Speed Stacker"
    case other = "Other"
}
